sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: z5DmRXWOvqq90JXtKHEa9Y9KlGd2ubGG1SP4Gj4sPpQblipbUfKKWXYWoKxOAuZasfWeDVhk2Ld5mUQXTCI3WVVXEycczLGxTP/v/DNmhf59aO00zZl4hYS6LQzw8GxaPMIsu0xGuAxenrcg+QGQCTsS80Z/x/EjnBikmPlq52eAs6H5yEAuzffdWOOiQB5eC1J25YIv06/24EJuvP0RzjbISv2UtWUSarDiGQCdZFX/6/W4hSY5fwTx8mpnfqhtPm7/+ExT6geURK04WvwrW6yy+U+XS/l9CvD06jXc2WMD16rnXSDiBdbJ/P36orbOZsReiIGqBGa9oVzhJTjrlo7U8j9SCB7v6Eefj1t4Wq/2mKaq+gFYovWSZ9Fr6RuXYm+tSAb68ZY/y4M0JjeEflRHKpVNlvROAXTj8qoE1cbEX1iXaSH/8TpRu1mJh/J+OSZd5grzy7R4eM2Ba4DTtioLsmXZ+sgitbR4Bzyf/t6l2oyNJ6Tgp/0ojrJ7RSn+kC41Naitnc1vaOq8Mf352JvQMAEyhVOW1s6w9LY0gjrHDocB583H36Xz3ZOXITQA3gN/pKd61LSwvdQLvfxPDsbO5Xz6VSXLqYaDiCCA+IotnpYQd2zvW+tUhEk5EU2GC9nmCN7c5+FlVXSnwCP44uw2Ymk8ZwRrhPHBZ7lIGAQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Stories-by-Foreign-Authors--Scandinavian_5336
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy